name: Security Audit

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        run: cargo audit

      - name: Check for vulnerable dependencies
        run: cargo audit --deny warnings
