name: Generate Table of Contents

on:
  push:
    paths:
      - 'README.md'
      - 'docs/**/*.md'

jobs:
  generate-toc:
    name: Generate TOC
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: 'README.md,docs'
          TOC_TITLE: '## Table of Contents'
          CREATE_PR: false
          COMMIT_MESSAGE: 'docs: update table of contents'
          COMMIT_NAME: 'github-actions[bot]'
          COMMIT_EMAIL: 'github-actions[bot]@users.noreply.github.com'
